import { stepGuidance, hideEarAnswer, visiblePattern } from './lesson-guidance.js';

const esc = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const noteName = note => note.replace('#', '♯').replace(/[0-8]$/, '');

export function renderLesson({ lesson: l, stepIndex, chapter, lessonNumber, lessonCount, done, bpm, looping, review, revealed, hintShown, icon, keyboard, title }) {
  const s = l.steps[stepIndex]; const guide = stepGuidance(s);
  const hiddenAnswer = hideEarAnswer(s, revealed);
  const isEar = s.mode === 'ear'; const isRhythm = s.mode === 'rhythm'; const isListening = s.mode === 'listen';
  const handGuide = s.handGuide || l.handGuide;
  return `<div class="lesson-topline"><a href="#path" class="back-link">${icon('back')} Learning path</a><span>LESSON ${String(lessonNumber).padStart(2, '0')} OF ${lessonCount}<span class="dot-sep">·</span>${esc(chapter.name)}</span><span class="tag">${icon('clock')} ${l.duration} min</span></div>
    ${title('YOUR KEYBOARD PRACTICE ROOM', esc(l.title), esc(l.description))}
    <div class="lesson-layout"><aside class="checkpoint-panel"><div class="section-heading"><h2>Little checkpoints</h2><span>${done.length}/${l.steps.length}</span></div><div class="checkpoint-progress" aria-label="${done.length} of ${l.steps.length} checkpoints complete">${l.steps.map((_, i) => `<i class="${done.includes(i) ? 'done' : ''}"></i>`).join('')}</div>
      <div class="checkpoint-list">${l.steps.map((step, i) => `<button class="checkpoint ${i === stepIndex ? 'selected' : ''}" data-action="step" data-step="${i}" ${i === stepIndex ? 'aria-current="step"' : ''}><span>${done.includes(i) ? icon('check') : i + 1}</span><span><strong>${esc(step.title)}</strong><small>${done.includes(i) ? 'Checkpoint saved' : i === stepIndex ? 'You are here' : esc(stepGuidance(step).label)}</small></span></button>`).join('')}</div>
      <div class="checkpoint-save">${icon('save')} Each completed step saves automatically.</div><div class="lesson-tip">${icon('leaf')}<h3>A friendly reminder</h3><p>${esc(l.tip)}</p></div><button class="text-button flag-button ${review ? 'flagged' : ''}" data-action="flag">${icon('flag')} ${review ? 'Saved for more practice' : 'Save for more practice'}</button>
    </aside><section class="practice-main">
      ${l.chapter === 'chords' ? `<div class="chord-lesson-link"><span>Try these shapes and make your own sequence.</span><a href="#chords">Open chord playground ${icon('arrow')}</a></div>` : ''}
      <div class="instruction-card clear-instructions"><div class="step-eyebrow"><span>CHECKPOINT ${stepIndex + 1} OF ${l.steps.length}</span><span class="step-mode ${s.mode}">${icon(isEar || isListening ? 'volume' : 'keys')} ${esc(guide.label)}</span></div>
        <div class="instruction-heading"><h2>${esc(s.title)}</h2><button id="play-demo" class="button primary" data-action="${isRhythm ? 'metronome' : 'play'}" aria-pressed="false">${icon(isRhythm ? 'pulse' : 'play')} ${esc(guide.button)}</button></div>
        <p class="task-now">${esc(guide.instruction)}</p><p class="instruction-body">${esc(s.body)}</p>
        <div class="practice-cue">${icon('spark')}<span>${esc(s.cue)}</span></div>
        ${s.mode === 'guided' && handGuide ? `<div class="hand-position"><strong>Your hand position</strong><p>${esc(handGuide)}</p></div>` : ''}
        <div class="practice-flow">${esc(guide.next)}</div>
        ${isListening ? `<div class="listen-next"><span>You can finish this checkpoint after listening once.</span><button class="button secondary" data-action="complete">${icon('check')} I’ve listened — continue</button></div>` : ''}
      </div>
      ${isEar ? `<section class="ear-support" aria-label="Ear-training help"><div><strong>A little help is always welcome</strong><p>The hidden notes are a practice choice, not an exam. Your Casio is not connected; compare the sounds yourself.</p></div><div class="ear-buttons"><button class="button secondary" data-action="ear-reference">${icon('volume')} Hear reference ${esc(s.reference)}</button><button class="button secondary" data-action="ear-hint" aria-expanded="${hintShown}">${hintShown ? 'Hide hint' : 'Give me a hint'}</button><button class="button primary" data-action="ear-reveal" aria-expanded="${revealed}">${revealed ? 'Hide answer & try again' : 'Reveal the answer'}</button></div>${hintShown ? `<p class="ear-hint" role="status">${esc(s.hint)}</p>` : ''}${revealed ? `<div class="ear-answer" role="status"><strong>Compare with this answer</strong><p>${esc(s.answer)}</p><small>Now replay the example with the notes visible, then try it on your keyboard.</small></div>` : ''}</section>` : ''}
      <div class="demo-card lesson-demonstration"><div class="demo-heading"><div><h3>${isRhythm ? 'Keep the clicks comfortable' : hiddenAnswer ? 'The answer is hidden for this exercise' : isListening ? 'A visual guide, if you want to follow along' : isEar ? 'Your revealed note guide' : 'These are the notes to play'}</h3><p>${isRhythm ? 'Tap along to the metronome; the keyboard below is optional.' : hiddenAnswer ? 'Mystery playback will not highlight the keys or show the note sequence.' : isListening ? 'You can watch these notes while listening. You do not need to play them yet.' : 'Read left to right. Play on your Casio after the example stops; pause whenever you need.'}</p></div></div>
        ${isRhythm ? '' : hiddenAnswer ? '<div class="hidden-melody"><span aria-hidden="true">♪ &nbsp; ? &nbsp; ♫</span><p>Listen first. Experiment with the keys below or on your Casio. Reveal the answer whenever you want.</p></div>' : `<div class="note-strip" aria-label="${isListening ? 'Example' : 'Practice'} notes with octave and beat counts">${visiblePattern(s, revealed).map((event, i) => `<div class="note-chip" data-index="${i}"><strong>${event.notes.length ? event.notes.map(noteName).join('<span> + </span>') : '—'}</strong><small>${event.notes.length ? event.notes.map(n => esc(n.replace('#', '♯'))).join(' · ') : 'rest'}</small><span>${event.beats} ${event.beats === 1 ? 'beat' : 'beats'}</span></div>`).join('')}</div><p class="note-reading-help"><strong>How to read this:</strong> each card is one key press (or one chord). Hold a “2 beats” note while counting 1–2; do not press it twice. A + means together; a dash means silence. C4 is middle C—the 4 is an octave number, not a finger number.${s.bass ? ` Keep ${esc(s.bass)} held underneath the moving notes, as the task describes.` : ''}</p>`}
        ${keyboard()}<div class="keyboard-caption"><span><i></i> Middle C = C4</span><span>Click a key to hear it · C3–B5 shown</span></div>
        <div class="transport">${!isRhythm ? `<button id="loop-button" class="button icon-button ${looping ? 'active' : ''}" data-action="loop" aria-pressed="${looping}" aria-label="Loop demonstration" title="Loop demonstration">${icon('loop')}</button>` : ''}<div class="tempo-control"><label for="tempo">${isListening ? 'Listening speed' : 'Practice speed'} <strong id="tempo-value">${bpm} BPM</strong></label><input type="range" id="tempo" min="40" max="100" step="5" value="${bpm}" aria-label="Practice speed in beats per minute"></div><button id="metronome" class="button metronome-button" data-action="metronome" aria-pressed="false">${icon('pulse')} <span>${isRhythm ? 'Start the metronome' : 'Metronome'}</span></button></div>
        <div class="demo-bottom"><span>No connection needed. This guide doesn’t listen to your playing.</span><span class="beat-indicator" aria-label="Metronome beat">${[0,1,2,3].map(() => '<i class="beat-dot"></i>').join('')}</span></div>
      </div>
      <div class="checkpoint-outcome"><strong>${isListening ? 'What counts as done?' : 'When should I continue?'}</strong><p>${esc(guide.doneWhen)}</p>${s.task ? `<small>Your checkpoint: ${esc(s.task)}</small>` : ''}</div>
      <div class="practice-actions"><div class="action-buttons"><button class="button quiet" data-action="easier">${isListening ? 'Explain this step' : 'Make it easier'}</button><button class="button secondary" data-action="repeat">${isListening ? 'Save to revisit' : 'Practise again'}</button><button class="button primary" data-action="complete">${icon('check')} ${done.includes(stepIndex) ? 'Continue' : esc(guide.completion)}</button></div></div>
      <div class="step-navigation"><button class="text-button" data-action="previous" ${stepIndex === 0 ? 'disabled' : ''}>${icon('back')} Previous step</button><span>${isEar ? 'Hints are part of learning.' : 'The notes are provided. Take your time.'}</span></div>
    </section></div>`;
}
