// Original exercises teach the skills; the linked publisher-hosted reference supplies the song melody.
export const scientistSource = {
  tutorial: 'https://blog.pianote.com/coldplay-the-scientist/',
  video: 'https://www.youtube.com/watch?v=yD0tj7vQd7s',
  score: 'https://pianote.s3.amazonaws.com/blog/pdf/The-Scientist-Lead-Sheet.pdf',
};
const pattern = text => text.split(' ').map(token => { const [pitch, beats] = token.split(':'); return { notes: pitch === '-' ? [] : pitch.split('+'), beats: Number(beats || 1) }; });
const drill = (title, body, cue, notes, extra = {}) => ({ title, body, cue, pattern: notes ? pattern(notes) : [], mode: 'guided', ...extra });
const reference = (title, body, cue, page, location, task) => ({ title, body, cue, mode: 'reference', pattern: [], reference: { page, location }, task });
const course = (id, title, description, steps, handGuide) => ({ id: `scientist-${id}`, title, description, chapter: 'scientist', goal: 'scientist', duration: 15, bpm: 50, steps, handGuide, tip: 'Spend 10–15 minutes on one small task. Repeat a checkpoint over several days if useful. Completion is your own check; Little Keys cannot hear your Casio.' });
const note = (hand, pitch, beat, duration) => ({ hand, note: pitch, beat, duration });
const shapes = [
  { name: 'Dm7', bass: 'D3', right: ['C4', 'F4', 'A4'] },
  { name: 'B♭', bass: 'Bb3', right: ['D4', 'F4', 'Bb4'] },
  { name: 'F', bass: 'F3', right: ['C4', 'F4', 'A4'] },
  { name: 'Fsus2', bass: 'F3', right: ['C4', 'F4', 'G4'] },
];
// Accompaniment studies: a deliberately simple pulse, not a transcription of the recording.
function chordStudy(chords, rightEvery = 1, leftEvery = 4) {
  return { bars: chords.map(c => c.name), events: chords.flatMap((c, bar) => [
    ...Array.from({length: 4 / leftEvery}, (_, i) => note('left', c.bass, bar * 4 + i * leftEvery, leftEvery)),
    ...Array.from({length: 4 / rightEvery}, (_, i) => c.right.map(n => note('right', n, bar * 4 + i * rightEvery, rightEvery))).flat(),
  ]) };
}
const cShape = {name: 'C', bass: 'C3', right: ['C4', 'E4', 'G4']};
const chordHands = 'Left hand: one comfortable finger on the lower bass note. Right hand: use the fingers listed in the task; move your whole hand if a stretch feels uncomfortable. B♭ is the black key immediately left of B.';
const readingHands = 'Right hand: begin around middle C. Choose fingers that let you reach the next notes without stretching; release and move between phrases. Use the source’s printed fingering where provided.';

export const scientistLessons = [
  course('keys', 'One new black key: B♭', 'Find the notes and relaxed hand positions for your song.', [
    drill('Find B-flat', 'Find the group of three black keys near middle C. B-flat (B♭) is the rightmost black key in that group, immediately to the left of B. Play A4, B♭4, and B4 slowly. B♭ and A♯ are two names for this same key; we use B♭ in this song.', 'Find the key first; the demonstration is an original note-finding exercise.', 'A4:2 Bb4:2 B4:2 Bb4:2', { handGuide: 'Right hand: try thumb on A4, index on B♭4, middle on B4. Keep your fingers relaxed.' }),
    drill('Walk through the song’s note family', 'Try F4–G4–A4–B♭4, then pause and reposition for C5–D5–E5–F5. This introduces the F-major note family. You do not need to learn a fast scale or thumb crossing now. Notice that B is flat, while the other letters here are white keys.', 'Two groups of four, with a pause to move your hand.', 'F4 G4 A4 Bb4 -:2 C5 D5 E5 F5:2', { handGuide: 'Right hand: 1–2–3–4 for each group. Release, move, then begin the next group with your thumb.' }),
    drill('Move without holding a stretch', 'Play C4, F4, and A4 separately. Release, then try them together if the shape feels comfortable. Do the same with D4, F4, and B♭4. Never keep your thumb pinned down while reaching. These two shapes prepare the chord changes in the next lesson.', 'Release → move → find the next shape.', 'C4 F4 A4 - D4 F4 Bb4 -', { handGuide: 'Right hand: try 1–3–5 for C–F–A and 1–2–5 for D–F–B♭. Play notes separately if the reach is uncomfortable.' }),
    drill('Find the bass notes', 'With your left hand, find D3, B♭3, and F3. Our starter exercises use B♭3 above F3 to stay within the displayed keyboard. This changes the bass register from some arrangements, while keeping the same harmony. Find each note before trying to change on a beat.', 'D → B♭ → F → F. One note at a time.', 'D3:4 Bb3:4 F3:4 F3:4', { handGuide: 'Left hand: use any comfortable finger, releasing and moving your hand between bass notes. B♭3 is just below middle C.' }),
  ], readingHands),
  course('shapes', 'The chords behind The Scientist', 'Learn the four main harmonies in comfortable positions.', [
    drill('Build D minor seven across your hands', 'Play D3 with your left hand. Place your right thumb on C4, middle finger on F4, and little finger on A4. Together, the four notes form D minor seven (Dm7). First find each note, then press both hands together. The right-hand shape alone is an F chord; the low D supplies the Dm7 sound.', 'Left: D. Right: C–F–A. Find the notes before adding rhythm.', '', { tracks: chordStudy([shapes[0]], 4), task: 'I found both hand positions and played them comfortably.' }),
    drill('Make the B-flat shape', 'Release the previous shape. Play left B♭3 and right D4–F4–B♭4. Try right fingers 1–2–5. Keep F as a visual landmark, but let your hand release and reposition freely. Practise the change from the previous checkpoint without a metronome first.', 'Two B-flat keys: one in each hand.', '', { tracks: chordStudy([shapes[1]], 4), task: 'I can find the B♭ shape without a strained reach.' }),
    drill('Meet F and its suspended neighbour', 'For F, play left F3 and right C4–F4–A4. For Fsus2, keep the left F and change the top right-hand note from A4 to G4. Try 1–3–5 for F and 1–3–4 for Fsus2. “Sus2” describes this change in chord colour; you do not need to memorise the theory yet.', 'Right-hand top note: A → G. Keep the movement small.', '', { tracks: chordStudy(shapes.slice(2), 4), task: 'I heard and played the difference between F and Fsus2.' }),
    drill('Join the four shapes slowly', 'Move through Dm7, B♭, F, and Fsus2, allowing a full four-count for each. These are the song’s main opening and verse harmonies. This is a simplified chord study: it does not contain the sung melody or every detail of the recording. Pause between shapes until they feel familiar.', 'Four shapes, then a rest. Aim for comfortable changes.', '', { tracks: chordStudy(shapes, 4), task: 'I can move through the four shapes twice with comfortable pauses.' }),
  ], chordHands),
  course('pulse', 'Keep a pulse while the bass changes', 'Use separate-hand playback, a count-in, and small practice loops.', [
    drill('Hold left, repeat right', 'Select “Right hand” and hear four gentle chord presses. Then select “Left hand” and hear one held bass note. Finally choose “Both hands”. On your Casio, hold the left note while the right repeats. Start after the four count-in clicks; the count-in returns at the start of every loop.', 'Left hand holds; right hand presses once per beat.', '', { tracks: chordStudy([shapes[0]]), task: 'I kept the bass down while playing four even right-hand presses.' }),
    drill('Make one change on the next first beat', 'Work on just Dm7 to B♭. Practise the hands separately, then together at 40–50 BPM. Move into the new shape on the next “1”. The bar-range controls let you repeat either bar or the pair. You can stop the example and practise at your own pace.', 'Count 1–2–3–4, then change on 1.', '', { tracks: chordStudy(shapes.slice(0,2)), task: 'I changed both hands together without rushing the last beat.' }),
    drill('Keep the whole loop steady', 'Use the four-bar chord study. Keep the left hand to one held note per bar and the right to one press per beat. Choose only the bars around a difficult change, then widen the range. Repeat at a comfortable speed; 76 BPM is a later reference tempo, not today’s requirement.', 'A slow steady loop is enough.', '', { tracks: chordStudy(shapes), task: 'I played the four-bar study twice with a steady count.' }),
    drill('Optional: two left taps for each right press', 'This optional coordination exercise uses repeated D notes in the left hand while the right repeats a chord. Count “1-and-2-and-3-and-4-and”: left on every number and “and”, right on numbers only. Practise tapping first. This prepares a busier accompaniment; the simple held-bass version is enough for your first song milestone.', 'Try the extra pulse only if the simpler version feels relaxed.', '', { tracks: chordStudy([shapes[0]], 1, 0.5), task: 'I explored the faster left-hand pulse, or chose the held-bass version for now.' }),
  ], chordHands),
  course('read', 'A small map for the melody', 'Learn just enough notation to use the linked song score.', [
    drill('Read upward from middle C', 'Open the note map below. The five-line staff is a picture of higher and lower notes. Middle C sits on a short extra line below it; D sits in the gap above C, and E on the bottom staff line. Follow this original C–D–E exercise while looking between the map and your keyboard.', 'Higher on the page means farther right on the keyboard.', 'C4:2 D4:2 E4:2 D4:2', { staffMap: true }),
    drill('Find the notes above E', 'On the treble staff, the lines from bottom to top are E–G–B–D–F; the spaces are F–A–C–E. The B-flat sign at the beginning of the song score tells you to play B-flat whenever B appears, unless another sign changes it. Use the note map whenever needed; this is not a memory test.', 'Follow the position, then check the B-flat reminder.', 'F4:2 A4:2 Bb4:2 C5:2', { staffMap: true }),
    drill('Count short sounds and space', 'A filled note with a stem usually lasts one beat here. A flag or beam makes it half a beat: count a number and “and” across each pair. A hollow note with a stem lasts two beats. A rest means leave space; a curved tie between the same pitch means keep holding, not press again. Tap this original exercise before playing it.', 'C on 1-and, D on 2, silence on 3, E on 4.', 'C4:0.5 C4:0.5 D4:1 -:1 E4:1', { staffMap: true }),
    reference('Find your starting place in the song', 'Open Pianote’s score using the button below. Page 1 begins with the chord introduction. The sung melody starts in the system marked 6. Follow the top lyric row for verse one, but use the staff for the notes. Locate bars 6–9 before playing; this is the first short-section target. A bar number is a location in this specific score, not a finger or beat count.', 'Reference checkpoint: open the score and find bars 6–9.', 1, 'Page 1 · system beginning at bar 6 · top lyric row', 'I found the first melody section in the reference.'),
  ], readingHands),
  course('phrases', 'Your first recognisable song section', 'Learn the opening melody in three small chunks using the reference.', [
    reference('First phrase: take only bar 6', 'Keep Pianote’s score open at bar 6 on page 1. Ignore the chord symbols for now: use only the single-note melody and the top lyric row. Locate each note using the map, tap its rhythm, then play with your right hand. Keep the opening rest. Stop at the bar line, even if you want to continue.', 'One bar only. Find notes → tap → play → repeat.', 1, 'Page 1 · bar 6 · opening rest and first melody phrase', 'I can play the first small phrase slowly twice.'),
    reference('Second phrase: work on bar 7', 'Move to bar 7 in the same system. Find the notes and rhythm before playing. Practise it alone, then join the last part of bar 6 to the start of bar 7. A pause to find your hand position is fine while learning; gradually shorten that pause. Use the original recording or source demonstration to check the phrasing.', 'Practise the join as well as the new notes.', 1, 'Page 1 · bar 7 · second melody phrase', 'I can play the second phrase and join it to the first.'),
    reference('Third phrase: finish bars 8–9', 'Learn bar 8 and the first ending at bar 9. Follow the top lyric row and the ending marked for the early repeats. Work on pitches first, then keep the longer ending note for its full written length. Stop here: the later alternate ending belongs to a later verse repetition.', 'Let the end of the phrase breathe.', 1, 'Page 1 · bars 8–9 · first ending', 'I can play the third phrase with its held ending.'),
    reference('Save your first song milestone', 'Join bars 6–9 using the top lyric row and first ending. Play right hand only at a speed where you can keep going. Aim for two recognisable rounds with the rests and held notes in place. This is a short section of the actual melody, not completion of the whole song. If a join interrupts you, save this lesson for more practice and revisit that pair of bars.', 'Your first milestone: three connected melody chunks.', 1, 'Page 1 · bars 6–9 · first short section', 'I played the opening section twice with my right hand.'),
  ], readingHands),
  course('support', 'Give your melody a simple bass', 'Keep the melody in your right hand and add light left-hand support.', [
    drill('Practise only the bass changes', 'For the short verse section, prepare one bass note for each main harmony: D, B♭, F, then F again. Use the chord symbols above the source melody to locate each change. This bass-only study gives you a simple starting accompaniment; it does not play the melody for you.', 'Left hand alone before trying the melody above it.', '', { tracks: { bars: shapes.map(s => s.name), events: shapes.map((s,i)=>note('left',s.bass,i*4,4)) }, task: 'I can find each bass note at a slow four-count.' }),
    reference('Add the bass to the first phrase', 'Return to bar 6. Put your left hand on the bass note for its chord and your right hand ready for the melody. Start the bass on the bar’s first beat, then enter the melody after its written rest. Hold the bass while the melody moves. Practise this small section alone; leave out the bass temporarily if it interrupts the melody.', 'The bass can start before the melody does.', 1, 'Page 1 · bar 6 · bass on beat 1, melody after its rest', 'I can hold a bass note while playing the first melody phrase.'),
    reference('Join the next two phrases', 'Add the bass changes to bars 7–9. Use one left-hand note at each chord change, holding it while your right hand plays the melody. At first, pause before each new bar to place both hands. Then practise only the last beat before a change and the first beat after it.', 'Keep the left hand simpler than the melody.', 1, 'Page 1 · bars 7–9 · chord changes above the melody', 'I joined the remaining phrases with simple bass notes.'),
    reference('Play your short section with both hands', 'Play the opening section, bars 6–9, with right-hand melody and one left bass note per chord change. Listen for the melody clearly above the bass; press the left notes gently. Two comfortable rounds count as the milestone. A pedal and the recording’s faster left-hand rhythm are optional later refinements.', 'A recognisable section, two hands, your own pace.', 1, 'Page 1 · bars 6–9 · melody plus simple bass', 'I played the short song section with both hands twice.'),
  ], chordHands),
  course('chorus', 'Build the chorus and its return', 'Learn the next melody section and the change that leads onward.', [
    reference('Find the chorus entrance', 'On page 1, find the chorus starting at bar 11. Learn the first small phrase with the right hand alone. Notice its entry and held notes rather than forcing every note onto a click. Use the note map and source rhythm; the opening verse melody is not a substitute for this section.', 'New melody, familiar practice method.', 1, 'Page 1 · chorus entrance at bar 11', 'I can play the first chorus phrase with my right hand.'),
    reference('Learn the chorus in pairs of bars', 'Continue through the chorus in two-bar pieces. Follow the repeat endings in the source: a repeated opening can lead to a different ending. Practise each ending separately, then practise the turn into it. Add a simple bass only after the melody feels familiar.', 'Mark where the second ending differs before joining it.', 1, 'Page 1 · bars 11–17 · chorus phrases and endings', 'I can connect the chorus phrases and choose the correct ending.'),
    drill('Prepare the C harmony', 'The return from the chorus introduces C harmony. Practise a plain C-major chord with a low C, then move to Dm7. This original transition study isolates the hand movement. When applying it to the song, follow the reference for the actual duration and melody rather than copying this study’s two-bar timing.', 'C is familiar. Practise the move back to Dm7.', '', { tracks: chordStudy([cShape, shapes[0]], 4), task: 'I can find C and move into the next chord comfortably.' }),
    reference('Join the chorus to the next section', 'Work through the chorus ending and the instrumental return. First practise the last two bars of the chorus, then the first two bars of the following section. Join them without restarting the whole song. If the instrumental texture is difficult, use the chord symbols to play a simple bass-and-chord version.', 'Practise the doorway between sections.', 1, 'Page 1 · bars 18–24 · chorus ending and instrumental return', 'I can finish the chorus and enter the next section.'),
  ], chordHands),
  course('whole', 'Make a map of the whole song', 'Add the remaining verse, repeated chorus, and ending.', [
    reference('Complete the first verse', 'Return to the first verse and follow each lyric row and its repeat ending in the reference. Your opening short section is the starting point; later rows can change the rhythm or phrase ending. Practise those differences instead of assuming every repeat is identical. Then join the complete verse to the chorus.', 'Reuse what is familiar; practise the changed endings.', 1, 'Page 1 · first verse repeats and transition into the chorus', 'I played the first verse and reached the chorus.'),
    reference('Learn the second verse', 'On page 2, locate the second verse beginning in the system marked 25. Use the same method: one phrase, two phrases, then a longer section. Check the new rhythm carefully. Keep the left hand to simple bass notes until the right-hand line is comfortable.', 'Similar harmony does not mean every melody rhythm is identical.', 2, 'Page 2 · second verse, systems marked 25 and 28', 'I can play the second verse in connected phrases.'),
    reference('Practise the repeat route', 'Follow the second verse into the returning chorus. The score’s D.S. al Coda tells you to return to the marked sign and later jump at “To coda” to the ending marked CODA. Trace that route with your finger before playing. If repeats feel confusing, use the song-map checklist below to track the sections in performance order.', 'Trace the route first; then practise its transitions.', 2, 'Page 2 · D.S. al Coda, returning chorus, and coda', 'I know which section comes next through the repeats.'),
    reference('Give the song a deliberate ending', 'Work on the final instrumental/vocal ending on page 2. Use the reference’s indicated repeats, then its final bars. You may simplify the accompaniment to held bass and chords while keeping the melody clear. Practise the last phrase by itself; slow and release deliberately at the end instead of stopping abruptly.', 'Learn how to finish, not just how to begin.', 2, 'Page 2 · ending systems marked 39, 44 and 48', 'I can play the ending and release the final sound deliberately.'),
  ], readingHands),
  course('performance', 'Play your simplified song', 'Connect the sections and make a complete personal performance.', [
    reference('Opening through the first chorus', 'Prepare your reference and choose a comfortable tempo. Play a simple chord introduction, then verse one and the first chorus. Keep the right-hand melody and simple left bass as your arrangement. Use the song map to stay oriented. Note a difficult transition and practise just that join before another run.', 'Introduction → verse one → chorus.', 1, 'Page 1 · opening, verse one, and first chorus', 'I connected the opening, first verse and chorus.'),
    reference('The middle of your song', 'Start from the instrumental return rather than the beginning. Continue into verse two and the returning chorus. Practise starting at this middle point so a mistake does not force you to restart the entire performance. Keep the accompaniment at the same simple level throughout.', 'Instrumental return → verse two → returning chorus.', 2, 'Pages 1–2 · instrumental return and second verse/chorus route', 'I can start from the middle and continue through the chorus.'),
    reference('Connect the last transition', 'Practise the final chorus transition into the ending, following the coda route. Begin two bars before the transition and continue two bars beyond it. Then play the whole final section. Pedal is optional: clear releases and balanced hands are enough for this simplified version.', 'Final chorus → instrumental ending → final release.', 2, 'Page 2 · coda and ending', 'I can reach and finish the ending without restarting.'),
    reference('Save a complete performance', 'Play from the introduction through both verses, the choruses, the instrumental links and the ending. Use the source and song map as much as you need. Keep a steady comfortable tempo; small mistakes are fine if you recover. Mark this checkpoint only after playing the complete simplified arrangement. Completing the earlier chord studies alone does not meet this milestone.', 'The goal is a whole simplified performance—not matching every detail of the studio recording.', 1, 'Both reference pages · whole simplified arrangement', 'I played the complete simplified song from beginning to end.'),
  ], readingHands),
];
