import { scientistSource, scientistLessons } from './scientist.js';
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const displayNote = note => note.replace('#','♯').replace('b','♭');
export const scoreLink = page => `${scientistSource.score}#page=${page || 1}`;
const external = (url, text, cls='button secondary') => `<a class="${cls}" href="${url}" target="_blank" rel="noopener noreferrer" data-action="source">${text} ↗</a>`;
export function songSources() {
  return `<div class="song-source-links">${external(scientistSource.tutorial, 'Pianote lesson')}${external(scientistSource.video, 'Watch the teacher')}${external(scoreLink(1), 'Open song score')}</div>`;
}
export function staffMap() {
  const letters = ['C','D','E','F','G','A','B♭','C','D','E','F','G','A'];
  return `<details class="staff-help"><summary>Need help reading the melody notes?</summary><p>This is a note-location map, not the song. Each step upward is the next letter. Use B♭ in this song. Middle C is C4.</p><div class="staff-scroll"><svg viewBox="0 0 760 180" role="img" aria-label="Treble staff note map from middle C4 to A5, using B-flat"><text x="15" y="113" font-size="58">𝄞</text><text x="59" y="104" font-size="24">♭</text>${[0,1,2,3,4].map(i=>`<line x1="55" x2="745" y1="${118-i*10}" y2="${118-i*10}" stroke="currentColor" opacity=".4"/>`).join('')}${letters.map((n,i)=>{const x=85+i*52,y=128-i*5;return `${i===0?`<line x1="${x-13}" x2="${x+13}" y1="128" y2="128" stroke="currentColor"/>`:''}${i===1?`<line x1="${x-13}" x2="${x+13}" y1="128" y2="128" stroke="currentColor" opacity="0"/>`:''}<ellipse cx="${x}" cy="${y}" rx="7" ry="5" fill="currentColor"/><line x1="${x+6}" x2="${x+6}" y1="${y}" y2="${y-27}" stroke="currentColor"/><text x="${x}" y="166" text-anchor="middle" font-size="14">${n}${i<7?'4':'5'}</text>`;}).join('')}</svg></div><p><strong>Rhythm key:</strong> filled head + stem = 1 beat; a flag/beam = ½ beat; hollow head + stem = 2 beats; hollow head without stem = 4 beats. A rest leaves silence. A tie joins the same pitch into one held sound. Count half beats as “1-and-2-and-3-and-4-and”.</p><p><strong>Fingers:</strong> thumb 1, index 2, middle 3, ring 4, little finger 5. Finger numbers are different from octave numbers such as C4.</p></details>`;
}
export function renderReference(step, icon, bpm) {
  return `<section class="song-reference" aria-label="Song reference and practice task"><div class="eyebrow">YOUR PLACE IN THE SONG</div><h3>${esc(step.reference.location)}</h3><p>Open the score beside Little Keys. Your checkpoint stays here when you return. The score includes the sung melody; the teacher video focuses on the accompaniment.</p><div class="song-source-links">${external(scoreLink(step.reference.page),'Open this score page','button primary')}${external(scientistSource.tutorial,'Open Pianote lesson')}${external(scientistSource.video,'Watch the teacher')}</div><p class="source-credit">Reference: Pianote / Lisa Witt, “The Scientist”. Opens at the source; internet required.</p>${staffMap()}<details class="song-map"><summary>Your whole-song route</summary><ol><li>Chord introduction</li><li>First verse, including its repeated phrases and alternate ending</li><li>First chorus and its return</li><li>Instrumental link</li><li>Second verse</li><li>Returning chorus</li><li>Instrumental/vocal ending and final release</li></ol><p>Follow the exact repeats and endings in your reference. D.S. means return to the sign; “To coda” sends you to the ending marked CODA on that return.</p></details><div class="reference-practice"><strong>A small 10–15 minute session</strong><p>2 minutes: locate and tap the phrase. 5 minutes: right hand. 3 minutes: left hand if this step asks for it. 2–5 minutes: join, repeat, and check your goal.</p></div><div class="transport"><button id="metronome" class="button secondary" data-action="metronome" aria-pressed="false">${icon('pulse')} <span>Metronome</span></button><div class="tempo-control"><label for="tempo">Your practice tempo <strong id="tempo-value">${bpm} BPM</strong></label><input type="range" id="tempo" min="40" max="100" step="1" value="${bpm}" aria-label="Practice speed in beats per minute"></div></div><p class="source-credit">This tempo controls Little Keys’ metronome. Use the external player’s own speed controls for its video. No song-melody audio is generated here.</p></section>`;
}
export function renderStudy(step, { icon, keyboard, bpm, looping, selection }) {
  const { hand, from, to, countIn } = selection;
  const study = step.tracks;
  const hands = ['left','right'].filter(h=>study.events.some(e=>e.hand===h));
  const available = hands.length === 2 ? ['both', ...hands] : hands;
  const choices = study.bars.map((name,i)=>`<option value="${i}">${i+1}: ${esc(name)}</option>`).join('');
  return `<section class="demo-card song-study" aria-label="Accompaniment study"><div class="demo-heading"><div><h3>Practise one hand, then both</h3><p>Original skill exercise. The actual song melody is in the linked reference.</p></div><button id="play-notes" class="button primary" data-action="play" aria-pressed="false">${icon('play')} Play the example</button></div><div class="study-options"><label>Hear<select id="study-hand">${available.map(h=>`<option value="${h}" ${h===hand?'selected':''}>${h==='both'?'Both hands':h==='left'?'Left hand':'Right hand'}</option>`).join('')}</select></label><label>From bar<select id="study-from">${choices.replace(`value="${from}"`,`value="${from}" selected`)}</select></label><label>Through bar<select id="study-to">${choices.replace(`value="${to}"`,`value="${to}" selected`)}</select></label><label class="count-in"><input type="checkbox" id="study-count-in" ${countIn?'checked':''}> Four-beat count-in</label></div><p id="study-status" role="status">${countIn?'Four clicks, then begin.':'Begin with the first sound.'} Loop repeats only your selected bars.</p><div class="study-bars">${study.bars.map((name,i)=>`<article class="study-bar ${i<from||i>to?'outside-range':''}" data-bar="${i}"><header><small>BAR ${i+1}</small><strong>${esc(name)}</strong></header>${hands.map(h=>`<div class="study-hand ${h}"><strong>${h==='left'?'Left · bass':'Right · chord'}</strong>${Object.entries(study.events.filter(e=>e.hand===h&&Math.floor(e.beat/4)===i).reduce((groups,e)=>{const key=`${e.beat-i*4}|${e.duration}`;(groups[key]||=[]).push(e.note);return groups;},{})).map(([key,notes])=>{const [start,duration]=key.split('|').map(Number);return `<p><span>${notes.map(displayNote).join(' + ')}</span><small>Beat ${start+1} · hold ${duration} ${duration===1?'beat':'beats'}</small></p>`;}).join('')}</div>`).join('')}</article>`).join('')}</div><p class="note-reading-help">Read each bar’s two hand parts together. “+” means press those notes together. A held left note continues while the right hand repeats. Beat 1.5 is the “and” after 1. Use the hand selector to hear either part alone.</p>${keyboard()}<div class="keyboard-caption"><span>Middle C = C4 · B♭ = A♯</span><span>Play on your Casio · click keys to preview</span></div><div class="transport"><button id="loop-button" class="button icon-button ${looping?'active':''}" data-action="loop" aria-pressed="${looping}" aria-label="Loop demonstration">${icon('loop')}</button><div class="tempo-control"><label for="tempo">Practice speed <strong id="tempo-value">${bpm} BPM</strong></label><input type="range" id="tempo" min="40" max="100" step="1" value="${bpm}" aria-label="Practice speed in beats per minute"></div><button id="metronome" class="button metronome-button" data-action="metronome" aria-pressed="false">${icon('pulse')} <span>Metronome</span></button></div><p class="source-credit">No microphone or cable. Mark the checkpoint after your own practice.</p></section>`;
}
export function scientistOverview({state, isDone, lessonRow, lessons, icon, title}) {
  const done = scientistLessons.filter(l=>isDone(state,l.id)).length;
  const milestones = [ ['scientist-phrases','Opening melody'], ['scientist-support','Opening with both hands'], ['scientist-performance','Whole simplified song'] ];
  const next = scientistLessons.find(l=>!isDone(state,l.id)) || scientistLessons[0];
  const needed=['cde','steady-beat','mary','c-chord','together'];
  return `${title('COLDPLAY · YOUR SONG PATH','Play The Scientist.','First a recognisable section. Then a whole simplified performance, one phrase at a time.')}<section class="song-path-hero"><div><span class="pill">${done} OF ${scientistLessons.length} SONG LESSONS COMPLETE</span><h2>A song you can grow into.</h2><p>Learn the chord shapes here. Use Pianote’s linked score for the melody, with a specific practice task and saved checkpoint at each step. Start with bars 6–9: three small melody chunks from the opening verse.</p><button class="button primary" data-action="lesson" data-id="${next.id}">${icon('play')} ${done?'Continue song path':'Start song preparation'}</button></div><ol class="song-milestones">${milestones.map(([id,name])=>`<li class="${isDone(state,id)?'done':''}">${icon(isDone(state,id)?'check':'music')}<span>${name}<small>${isDone(state,id)?'Checkpoint milestone saved':'Learn at your own pace'}</small></span></li>`).join('')}</ol></section><div class="song-prerequisites"><strong>A comfortable starting point</strong><p>Find notes, keep a slow beat, play a simple melody, and try each hand separately. Ear training is optional.</p><div>${needed.map(id=>{const l=lessons.find(l=>l.id===id);return `<button class="tag" data-action="lesson" data-id="${id}">${isDone(state,id)?'✓ ':''}${esc(l.title)}</button>`;}).join('')}</div></div><section class="song-reference"><h3>Your song reference</h3><p>Pianote’s free lesson and source-hosted score accompany this path. Keep the score open for the actual melody and section endings. The in-app examples are chord and coordination studies, not a complete song transcription.</p>${songSources()}</section><div class="song-path-lessons">${scientistLessons.map(l=>lessonRow(l,lessons.indexOf(l))).join('')}</div>`;
}
